version: '3'

services:
  db:
    image: mongo # container image to be used
    restart: always
    ports: # expose ports in “host:container” format
      - 27017:27017
    environment: #env variables to pass into the container
      MONGODB_DATABASE: the-coffee-app-be
    networks:
      - node-network

  # mongo-express:
  #   image: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: db
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
  #   networks:
  #     - node-network
networks:
  node-network:
    driver: bridge
