#docker-compose file
version: '3'

services:
  nestapp:
    container_name: the-coffee-app
    image: the-coffee-app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env